"""
Phishing Link Analyzer — Automated Setup
=========================================
One command to rule them all:  python setup.py

  Step 1 — pip install -r requirements.txt
  Step 2 — Collect API keys / config interactively
  Step 3 — Push n8n_phishing_alert_workflow.json to n8n via REST API
  Step 4 — Activate the workflow and write N8N_WEBHOOK_URL to .env
"""

import json
import os
import subprocess
import sys
import time

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ENV_FILE = os.path.join(BASE_DIR, ".env")
WORKFLOW_FILE = os.path.join(BASE_DIR, "n8n_phishing_alert_workflow.json")
REQUIREMENTS_FILE = os.path.join(BASE_DIR, "requirements.txt")

BANNER = """
##############################################################
  Phishing Link Analyzer — Automated Setup v2
##############################################################
  This script will:
    1. Install all Python dependencies
    2. Ask for your API keys and configuration
    3. Push the n8n workflow and activate it
    4. Write everything to .env

  Press Ctrl+C at any time to cancel.
##############################################################
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _ok(msg: str) -> None:
    print(f"  [OK]  {msg}")


def _err(msg: str) -> None:
    print(f"  [ERR] {msg}")


def _info(msg: str) -> None:
    print(f"        {msg}")


def load_existing_env() -> dict:
    values = {}
    if not os.path.exists(ENV_FILE):
        return values
    with open(ENV_FILE) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, val = line.partition("=")
                values[key.strip()] = val.strip()
    return values


def prompt(label: str, default: str = "", secret: bool = False) -> str:
    if secret and len(default) > 4:
        display = "*" * 6 + default[-4:]
    else:
        display = default
    hint = f" [{display}]" if display else ""
    try:
        value = input(f"  {label}{hint}: ").strip()
    except (KeyboardInterrupt, EOFError):
        print("\n\nSetup cancelled.")
        sys.exit(0)
    return value if value else default


def write_env(values: dict) -> None:
    lines = [
        "# Phishing Link Analyzer — environment config",
        "# Auto-generated by setup.py  (add .env to .gitignore)",
        "",
    ]
    for key, val in values.items():
        if val:
            lines.append(f"{key}={val}")
    with open(ENV_FILE, "w") as f:
        f.write("\n".join(lines) + "\n")
    _ok(f".env written → {ENV_FILE}")


# ---------------------------------------------------------------------------
# Step 1 — Install dependencies
# ---------------------------------------------------------------------------

def run_pip_install() -> None:
    print("\n[ STEP 1/4 ]  Installing dependencies")
    print(f"  Running: pip install -r requirements.txt\n")
    try:
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "-r", REQUIREMENTS_FILE]
        )
        print()
        _ok("All packages installed.")
    except subprocess.CalledProcessError as exc:
        _err(f"pip install failed (exit {exc.returncode}).")
        _info("Fix the error above, then re-run setup.py.")
        sys.exit(exc.returncode)


# ---------------------------------------------------------------------------
# Step 2 — Collect config
# ---------------------------------------------------------------------------

def collect_config(existing: dict) -> dict:
    print("\n[ STEP 2/4 ]  Configuration")
    print("  Press Enter to keep the value shown in [brackets].\n")

    print("  -- Anthropic --")
    _info("Get your key at: https://console.anthropic.com/keys")
    anthropic_key = prompt("ANTHROPIC_API_KEY", existing.get("ANTHROPIC_API_KEY", ""), secret=True)

    print()
    print("  -- n8n --")
    _info("n8n API key: open n8n → Settings → n8n API → Create an API key")
    n8n_url = prompt(
        "N8N_URL (your n8n instance URL)",
        existing.get("N8N_URL", "http://localhost:5678"),
    )
    n8n_api_key = prompt("N8N_API_KEY", existing.get("N8N_API_KEY", ""), secret=True)

    print()
    print("  -- Telegram --")
    _info("Bot token: message @BotFather on Telegram → /newbot")
    _info("Chat ID  : message @userinfobot on Telegram to find yours")
    telegram_token = prompt("TELEGRAM_BOT_TOKEN", existing.get("TELEGRAM_BOT_TOKEN", ""), secret=True)
    telegram_chat_id = prompt("TELEGRAM_CHAT_ID", existing.get("TELEGRAM_CHAT_ID", ""))

    return {
        "ANTHROPIC_API_KEY": anthropic_key,
        "N8N_URL": n8n_url,
        "N8N_API_KEY": n8n_api_key,
        "TELEGRAM_BOT_TOKEN": telegram_token,
        "TELEGRAM_CHAT_ID": telegram_chat_id,
        "N8N_WEBHOOK_URL": existing.get("N8N_WEBHOOK_URL", ""),
    }


# ---------------------------------------------------------------------------
# Step 3 — Push n8n workflow via REST API
# ---------------------------------------------------------------------------

def push_workflow(n8n_url: str, api_key: str) -> str:
    """
    Push n8n_phishing_alert_workflow.json to the n8n instance.
    Returns the live webhook URL or empty string on failure.
    """
    import requests as req  # guaranteed available after pip install

    print("\n[ STEP 3/4 ]  Pushing workflow to n8n")

    if not os.path.exists(WORKFLOW_FILE):
        _err(f"Workflow file not found: {WORKFLOW_FILE}")
        return ""

    headers = {
        "Content-Type": "application/json",
        "X-N8N-API-KEY": api_key,
    }

    with open(WORKFLOW_FILE) as f:
        workflow = json.load(f)

    # Strip local ID so n8n generates a fresh one
    workflow.pop("id", None)

    base = n8n_url.rstrip("/")

    # --- Create workflow ---
    try:
        resp = req.post(
            f"{base}/api/v1/workflows",
            json=workflow,
            headers=headers,
            timeout=15,
        )
        resp.raise_for_status()
    except req.exceptions.ConnectionError:
        _err(f"Cannot reach n8n at {base}. Is it running?")
        _info("Import manually: Workflows → Import from file → n8n_phishing_alert_workflow.json")
        return ""
    except req.exceptions.HTTPError as exc:
        _err(f"n8n returned {exc.response.status_code}: {exc.response.text[:200]}")
        _info("Check your N8N_API_KEY and that the API is enabled in n8n Settings.")
        return ""
    except Exception as exc:
        _err(f"Unexpected error: {exc}")
        return ""

    data = resp.json()
    # n8n may nest the object under a 'data' key depending on version
    workflow_obj = data.get("data", data)
    workflow_id = workflow_obj.get("id")

    if not workflow_id:
        _err("Workflow created but could not parse the workflow ID from the response.")
        return ""

    _ok(f"Workflow created (ID: {workflow_id})")

    # --- Activate workflow ---
    try:
        act = req.post(
            f"{base}/api/v1/workflows/{workflow_id}/activate",
            headers=headers,
            timeout=15,
        )
        act.raise_for_status()
        _ok("Workflow activated.")
    except Exception as exc:
        _err(f"Activation failed: {exc}")
        _info("Activate manually in the n8n UI.")

    webhook_url = f"{base}/webhook/phishing-alert"
    _ok(f"Webhook URL: {webhook_url}")
    return webhook_url


# ---------------------------------------------------------------------------
# Step 4 — Write .env
# ---------------------------------------------------------------------------

def finalize(config: dict) -> None:
    print("\n[ STEP 4/4 ]  Writing .env")
    write_env(config)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    print(BANNER)

    # Step 1
    run_pip_install()

    # Step 2
    existing = load_existing_env()
    config = collect_config(existing)

    # Step 3
    if config.get("N8N_URL") and config.get("N8N_API_KEY"):
        webhook_url = push_workflow(config["N8N_URL"], config["N8N_API_KEY"])
        if webhook_url:
            config["N8N_WEBHOOK_URL"] = webhook_url
    else:
        print("\n[ STEP 3/4 ]  Skipping n8n push — N8N_URL or N8N_API_KEY not provided.")
        _info("Re-run setup.py after configuring n8n to push the workflow automatically.")

    # Step 4
    finalize(config)

    # Done
    print()
    print("=" * 62)
    print("  Setup complete! Run the analyzer with:")
    print()
    print("    python main.py https://suspicious-site.com")
    print()
    if not config.get("N8N_WEBHOOK_URL"):
        print("  NOTE: N8N_WEBHOOK_URL is empty — Telegram alerts are disabled.")
        print("        Push the workflow to n8n, then re-run: python setup.py")
    print("=" * 62)
    print()


if __name__ == "__main__":
    main()
